baseURL = 'https://parsops.com/'
defaultContentLanguage = 'fa'
theme = 'parsops'

[languages]
  [languages.en]
    contentDir = 'content/en'
    disabled = true
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'ParsOps — DevOps as a Service. Simplified.'
    weight = 1

  [languages.fa]
    contentDir = 'content/fa'
    disabled = false
    languageCode = 'fa-IR'
    languageDirection = 'rtl'
    languageName = 'فارسی'
    title = 'پارس‌آپس — دواپس به‌عنوان سرویس. ساده‌شده.'
    weight = 1

  [languages.de]
    contentDir = 'content/de'
    disabled = true
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    title = 'ParsOps — DevOps als Service. Vereinfacht.'
    weight = 3
